version: '3'
services:
#  soldatbrbot:
#    build: .
#    volumes:
#      - .:/app
#    ports:
#      - 3000:3000
#    networks:
#      - bot-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .docker.env
    volumes:
      - ./.data:/data/db
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
