version: '3'
services:
  bot:
    build: .
    ports:
      - 3000:3000
      - 4040:4040
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - bot-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .mongo.env
    volumes:
      - ./.data:/data/db
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
