version: '3'
services:
#  soldatbrbot:
#    build: .
#    ports:
#      - 3000:3000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .docker.env
    volumes:
      - ./.data:/data/db
